name: CI/CD Pipeline for Java Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Zaibi72622002@
          MYSQL_DATABASE: softwaretesting
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    # Step 3: Install Maven dependencies
    - name: Install dependencies
      run: mvn install

    # Step 4: Wait for MySQL to be ready
    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -u root -pZaibi72622002@ --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    # Step 5: Run the tests
    - name: Run JUnit tests
      run: mvn test
